import Link from 'next/link';

const items = ['Junk removal','Eviction cleanouts','Apartment cleanouts','House cleanouts','Construction debris removal','Trash removal','Furniture removal','Appliance removal','Garage + outdoor junk','Commercial junk removal'];

export default function ServicesPage(){return <>
<section className="page-hero"><div className="container"><div className="eyebrow">Our Services</div><h1>WE HANDLE THE<br/><span>HEAVY STUFF.</span></h1><p>Fast, reliable junk removal and cleanout services throughout Metro Atlanta.</p></div></section>
<section className="section section-cream"><div className="container"><div className="eyebrow dark">What We Remove</div><h2>JUNK, TRASH,<br/>CLEANOUTS + MORE.</h2><div className="service-list">{items.map(item=><div className="service-item" key={item}>{item}</div>)}</div><p className="section-lead" style={{marginTop:28}}>Don&apos;t see your job listed? Send us a photo and we&apos;ll let you know if we can take it.</p></div></section>
<section className="section pricing-section"><div className="container"><div className="pricing-heading"><div><div className="eyebrow">Pricing</div><h2>STARTING AT<br/><span>$128.</span></h2></div><p>Small pickups and light loads start at $128 — including jobs like washer and dryer hauling. Pricing is based on the space your items take up on the truck and may vary based on item type, access, disposal requirements and job conditions.</p></div><div className="pricing-footer" style={{marginTop:'34px'}}><p className="pricing-note">For all inquiries and the most accurate quote, contact us. Call or send an email and tell us what you need removed.</p><div style={{display:'flex',gap:'14px',flexWrap:'wrap'}}><a href="tel:+14705402892" className="btn">Call (470) 540-2892</a><Link href="/contact" className="btn">Send an Email →</Link></div></div></div></section>
</>}
