import Link from 'next/link';

const items = ['Junk removal','Eviction cleanouts','Apartment cleanouts','House cleanouts','Construction debris removal','Trash removal','Furniture removal','Appliance removal','Garage + outdoor junk','Commercial junk removal'];

export default function ServicesPage(){return <>
<section className="page-hero"><div className="container"><div className="eyebrow">Our Services</div><h1>WE HANDLE THE<br/><span>HEAVY STUFF.</span></h1><p>Fast, reliable junk removal and cleanout services throughout Metro Atlanta.</p></div></section>
<section className="section section-cream"><div className="container"><div className="eyebrow dark">What We Remove</div><h2>JUNK, TRASH,<br/>CLEANOUTS + MORE.</h2><div className="service-list">{items.map(item=><div className="service-item" key={item}>{item}</div>)}</div><p className="section-lead" style={{marginTop:28}}>Don&apos;t see your job listed? Send us a photo and we&apos;ll let you know if we can take it.</p></div></section>
<section aria-label="Disappear It junk removal job" style={{background:'#0c0c0c',padding:'0'}}><div className="container" style={{paddingTop:'54px',paddingBottom:'54px'}}><figure style={{margin:0,width:'100%'}}><img src="/images/residential-cleanout-before.jpg" alt="Residential junk removal load ready for Disappear It pickup" style={{display:'block',width:'100%',height:'auto',objectFit:'contain'}}/></figure></div></section>
<section className="section pricing-section"><div className="container"><div className="pricing-heading"><div><div className="eyebrow">Pricing</div><h2><span>$128.</span></h2></div><p>Washer + dryer hauling is one example of a job at this rate. Final pricing is based on how much space your items take up on the truck.</p></div><div className="pricing-footer" style={{marginTop:'34px'}}><p className="pricing-note">For the most accurate quote, contact us with details about what you need removed.</p><div style={{display:'flex',gap:'14px',flexWrap:'wrap'}}><a href="tel:+14705402892" className="btn">Call (470) 540-2892</a><Link href="/contact" className="btn">Email Us →</Link></div></div></div></section>
</>}
