import Link from 'next/link';
import ServicesStrip from '../components/ServicesStrip';

const services = [
  ['Junk Removal','Single items, bulk junk and full-load removal.'],
  ['Eviction Clean-outs','Fast property clear-outs when you need the space ready.'],
  ['Apartment + House Clean-outs','Move-outs, whole-home clean-outs and unwanted contents.'],
  ['Construction Debris','Non-hazardous renovation and construction debris removal.'],
  ['Trash Removal','Bulk trash, bagged waste and unwanted items hauled away.'],
  ['And More','Furniture, appliances, garage junk, outdoor items and commercial loads.'],
];
const serviceAreas = ['Fayetteville, GA','Jonesboro, GA','Stockbridge, GA','McDonough, GA','Morrow, GA','Fairburn, GA','Atlanta, GA','South Fulton, GA','College Park, GA','Riverdale, GA','East Point, GA','Hapeville, GA'];

const Spark = ({size=18}:{size?:number}) => <span aria-hidden="true" style={{display:'inline-block',fontSize:size,lineHeight:1,color:'var(--gold-soft)'}}>✦</span>;

const TrustIcon = ({type}:{type:'shield'|'home'|'building'|'pin'}) => {
  if(type==='shield') return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3 26 7v7c0 7-4 12-10 15C10 26 6 21 6 14V7l10-4Z"/><path d="m11.5 15.5 3 3 6-7"/></svg>;
  if(type==='home') return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="m4 15 12-10 12 10"/><path d="M7 13v15h18V13"/><path d="M13 28v-8h6v8"/></svg>;
  if(type==='building') return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 28V5h18v23"/><path d="M4 28h24M11 10h3M18 10h3M11 15h3M18 15h3M11 20h3M18 20h3"/></svg>;
  return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M26 13c0 8-10 16-10 16S6 21 6 13a10 10 0 1 1 20 0Z"/><circle cx="16" cy="13" r="3"/></svg>;
};

export default function HomePage(){return <>
<section className="hero split-hero" style={{background:'#080808',borderBottom:'1px solid var(--line)'}}>
  <div className="split-hero-grid" style={{display:'grid',gridTemplateColumns:'42% 58%',minHeight:'clamp(620px,78vh,820px)'}}>
    <div className="split-hero-copy" style={{display:'flex',alignItems:'flex-start',justifyContent:'flex-end',background:'#080808'}}>
      <div style={{width:'min(100%,560px)',padding:'18px 44px 54px 28px'}}>
        <div style={{marginBottom:'28px'}}><img src="/images/disappear-it-logo.png" alt="Disappear It Junk & Trash Removal" style={{display:'block',width:'clamp(180px,16vw,220px)',height:'auto'}}/></div>
        <div className="eyebrow">Metro Atlanta Junk Removal</div>
        <h1>WE HANDLE THE<br/><span>HEAVY STUFF.</span></h1>
        <p style={{maxWidth:'520px'}}>Fast, reliable junk removal and clean-out services throughout Metro Atlanta — so you don&apos;t have to do the heavy lifting.</p>
        <div className="hero-actions"><Link className="btn" href="/contact">Get a Free Quote →</Link><a className="text-link" href="tel:+14705402892">Call Us</a><a className="text-link" href="mailto:junkdisappears@gmail.com">Email Us</a></div>
      </div>
    </div>
    <div className="split-hero-image" style={{position:'relative',overflow:'hidden',background:'#111'}}>
      <img src="/images/loaded-truck-haul.png" alt="Loaded Disappear It junk removal truck" style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',objectPosition:'center'}}/>
      <div aria-hidden="true" style={{position:'absolute',inset:0,background:'linear-gradient(90deg,rgba(8,8,8,.18),transparent 26%)'}}/>
    </div>
  </div>
</section>
<section className="micro-strip trust-strip"><div className="container micro-grid trust-grid"><div className="trust-item"><TrustIcon type="shield"/><div><strong>Licensed + Insured</strong><span>Professional. Reliable. Ready.</span></div></div><div className="trust-item"><TrustIcon type="home"/><div><strong>Residential</strong><span>Homeowners + Renters</span></div></div><div className="trust-item"><TrustIcon type="building"/><div><strong>Commercial</strong><span>Businesses + Property Teams</span></div></div><div className="trust-item"><TrustIcon type="pin"/><div><strong>Metro Atlanta</strong><span>Local + Surrounding Areas</span></div></div></div></section>
<ServicesStrip />
<section className="section section-cream" style={{paddingTop:'82px',paddingBottom:'82px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'4%',top:'28px',fontSize:'120px',lineHeight:1,color:'var(--gold)',opacity:.055}}>✦</span><div className="container editorial-split"><div><div style={{display:'flex',alignItems:'center',gap:'12px'}}><div className="eyebrow dark">Services</div><span aria-hidden="true" style={{height:'1px',width:'46px',background:'var(--gold)',opacity:.55}}/></div><h2>JUNK, TRASH,<br/>CLEAN-OUTS + MORE.</h2></div><div className="service-list-editorial">{services.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}<Link className="editorial-link" href="/services">View all services →</Link></div></div></section>
<section className="brand-statement" style={{paddingTop:'58px',paddingBottom:'58px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'7%',top:'50%',transform:'translateY(-50%)',fontSize:'190px',lineHeight:1,color:'#090909',opacity:.09}}>✦</span><div className="container" style={{position:'relative',zIndex:1}}><div style={{display:'flex',alignItems:'center',gap:'16px',marginBottom:'18px'}}><Spark size={20}/><span aria-hidden="true" style={{display:'block',height:'1px',width:'80px',background:'#090909',opacity:.4}}/></div><h2>YOU&apos;LL NEVER<br/>SEE IT AGAIN.</h2></div></section>
<section className="section process-section" style={{paddingTop:'82px',paddingBottom:'82px'}}><div className="container"><div className="process-intro"><div style={{display:'flex',alignItems:'center',gap:'12px',marginBottom:'8px'}}><Spark size={13}/><span aria-hidden="true" style={{display:'block',height:'1px',width:'44px',background:'var(--gold-soft)',opacity:.55}}/></div><h2>THREE STEPS.<br/>THAT&apos;S IT.</h2><p className="section-lead">Every job is different. Send us photos of what you need gone and we&apos;ll review the load, confirm availability and provide a quote.</p></div><div className="process-grid"><article><span>01</span><h3>Send us what you need gone.</h3><p>Share photos, your location and a quick description.</p></article><article><span>02</span><h3>Get your quote.</h3><p>We review the job and confirm pricing and availability.</p></article><article><span>03</span><h3>We handle the rest.</h3><p>We show up, load it and haul it away.</p></article></div></div></section>
<section className="section work-section" style={{paddingTop:'82px',paddingBottom:'82px'}}><div className="container"><div className="editorial-split work-heading"><div><div className="eyebrow">Our Work</div><h2>THE JUNK WAS THERE.<br/>NOW IT&apos;S NOT.</h2></div><div><p className="section-lead">Real transformations from completed Disappear It jobs throughout Metro Atlanta.</p><Link className="editorial-link light" href="/our-work">See our work →</Link></div></div><div className="work-showcase" style={{gridTemplateColumns:'1fr'}}><div className="work-stack"><div className="photo-card"><img src="/images/dunwoody-crossing.PNG" alt="Disappear It at Dunwoody Crossing"/></div><div className="photo-card"><img src="/images/dunwoody-cleanout-before.png" alt="Dunwoody Crossing cleanout before"/></div><div className="photo-card"><img src="/images/dunwoody-cleanout-after.png" alt="Dunwoody Crossing cleanout after"/></div></div></div></div></section>
<section className="section owner-section" style={{paddingTop:'74px',paddingBottom:'74px',background:'#0c0c0c',borderTop:'1px solid rgba(255,255,255,.1)',borderBottom:'1px solid rgba(255,255,255,.1)',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',left:'3%',bottom:'-34px',fontSize:'150px',lineHeight:1,color:'var(--gold-soft)',opacity:.045}}>✦</span><div className="container" style={{display:'grid',gridTemplateColumns:'minmax(0,1.45fr) minmax(220px,.55fr)',gap:'clamp(36px,7vw,92px)',alignItems:'center',position:'relative',zIndex:1}}><div className="owner-copy" style={{maxWidth:'720px'}}><div className="eyebrow">Owner Operated</div><h2 style={{marginBottom:'22px'}}>LOCAL. RELIABLE.<br/>BUILT TO GET IT GONE.</h2><p style={{maxWidth:'640px',color:'#b9b1a6',margin:'0 0 12px'}}>Disappear It is locally owned and operated by Aaron Miller, serving homes, apartments, property managers and businesses across Metro Atlanta with dependable junk removal and clean-out support.</p><p style={{maxWidth:'640px',color:'#b9b1a6',margin:'0'}}>From single-item pickups to larger clean-outs, the goal is simple: show up, handle the heavy work and leave you with your space back.</p></div><figure style={{margin:0,width:'min(100%,280px)',justifySelf:'end',alignSelf:'end'}}><img src="/images/disappear-it-ceo.jpeg" alt="Aaron Miller, owner of Disappear It Junk & Trash Removal" style={{width:'100%',height:'auto',display:'block',objectFit:'cover'}}/><figcaption style={{paddingTop:'14px',borderTop:'1px solid rgba(255,255,255,.14)',marginTop:'14px'}}><strong style={{display:'block',fontSize:'.88rem',letterSpacing:'.04em'}}>Aaron Miller</strong><span style={{display:'block',fontSize:'.65rem',letterSpacing:'.12em',textTransform:'uppercase',color:'#9f978c',marginTop:'4px'}}>Owner · Disappear It Junk & Trash Removal</span></figcaption></figure></div></section>
<section className="commercial-section" style={{paddingTop:'74px',paddingBottom:'74px'}}><div className="container commercial-grid"><div><div className="eyebrow dark">Commercial</div><h2>BUILT FOR BIGGER JOBS.</h2></div><div><p>Reliable junk removal and clean-out support for apartment communities, property managers and businesses.</p><Link className="btn btn-dark" href="/commercial">Commercial Services →</Link></div></div></section>
<section className="section area-section" style={{paddingTop:'82px',paddingBottom:'82px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'5%',bottom:'-28px',fontSize:'145px',lineHeight:1,color:'var(--gold-soft)',opacity:.045}}>✦</span><div className="container editorial-split" style={{position:'relative',zIndex:1}}><div><div className="eyebrow">Service Area</div><h2>METRO ATLANTA<br/>+ SURROUNDING AREAS.</h2><p className="section-lead">These are communities we serve frequently, but service is not limited to this list. Send your location and we&apos;ll confirm availability.</p></div><div className="area-list">{serviceAreas.map(area=><span key={area}>{area}</span>)}</div></div></section>
<section className="final-cta" style={{paddingTop:'64px',paddingBottom:'64px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',left:'4%',top:'50%',transform:'translateY(-50%)',fontSize:'120px',lineHeight:1,color:'#090909',opacity:.07}}>✦</span><div className="container cta-grid" style={{position:'relative',zIndex:1}}><div><h2>READY TO CLEAR IT OUT?</h2><p>Fast. Reliable. Professional. Licensed + Insured.</p></div><div className="cta-actions"><Link className="btn btn-dark" href="/contact">Get a Free Quote →</Link><a className="cta-phone" href="tel:+14705402892">Call Us</a><a className="cta-phone" href="mailto:junkdisappears@gmail.com">Email Us</a></div></div></section>
</>}
