import Link from 'next/link';
import ServicesStrip from '../components/ServicesStrip';

const services = [
  ['Junk Removal','Single items, bulk junk and full-load removal.'],
  ['Eviction Clean-outs','Fast property clear-outs when you need the space ready.'],
  ['Apartment + House Clean-outs','Move-outs, whole-home clean-outs and unwanted contents.'],
  ['Construction Debris','Non-hazardous renovation and construction debris removal.'],
  ['Trash Removal','Bulk trash, bagged waste and unwanted items hauled away.'],
  ['And More','Furniture, appliances, garage junk, outdoor items and commercial loads.'],
];
const serviceAreas = ['Fayetteville, GA','Jonesboro, GA','Stockbridge, GA','McDonough, GA','Morrow, GA','Fairburn, GA','Atlanta, GA','South Fulton, GA','College Park, GA','Riverdale, GA','East Point, GA','Hapeville, GA'];

const Spark = ({size=18}:{size?:number}) => <span aria-hidden="true" style={{display:'inline-block',fontSize:size,lineHeight:1,color:'var(--gold-soft)'}}>✦</span>;

export default function HomePage(){return <>
<section className="hero urban-hero" style={{paddingTop:'12px',position:'relative',overflow:'hidden',minHeight:'clamp(620px,78vh,820px)',backgroundImage:"linear-gradient(90deg, rgba(7,7,7,.94) 0%, rgba(7,7,7,.82) 42%, rgba(7,7,7,.36) 72%, rgba(7,7,7,.18) 100%), linear-gradient(0deg, rgba(7,7,7,.55) 0%, rgba(7,7,7,0) 48%), url('/images/loaded-truck-haul.png')",backgroundSize:'cover',backgroundPosition:'center 55%'}}><div className="container" style={{maxWidth:'1180px',width:'100%',position:'relative',zIndex:1}}><div className="hero-copy" style={{paddingTop:'18px',paddingBottom:'54px',maxWidth:'700px'}}><div style={{marginBottom:'28px'}}><img src="/images/disappear-it-logo.png" alt="Disappear It Junk & Trash Removal" style={{display:'block',width:'clamp(180px,16vw,220px)',height:'auto'}}/></div><div className="eyebrow">Metro Atlanta Junk Removal</div><h1>WE HANDLE THE<br/><span>HEAVY STUFF.</span></h1><p style={{maxWidth:'620px'}}>Fast, reliable junk removal and clean-out services throughout Metro Atlanta — so you don&apos;t have to do the heavy lifting.</p><div className="hero-actions"><Link className="btn" href="/contact">Get a Free Quote →</Link><a className="text-link" href="tel:+14705402892">Call Us</a><a className="text-link" href="mailto:junkdisappears@gmail.com">Email Us</a></div></div></div></section>
<section className="micro-strip"><div className="container micro-grid"><span>Licensed + Insured</span><span>Residential</span><span>Commercial</span><span>Metro Atlanta</span></div></section>
<ServicesStrip />
<section className="section section-cream" style={{paddingTop:'82px',paddingBottom:'82px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'4%',top:'28px',fontSize:'120px',lineHeight:1,color:'var(--gold)',opacity:.055}}>✦</span><div className="container editorial-split"><div><div style={{display:'flex',alignItems:'center',gap:'12px'}}><div className="eyebrow dark">Services</div><span aria-hidden="true" style={{height:'1px',width:'46px',background:'var(--gold)',opacity:.55}}/></div><h2>JUNK, TRASH,<br/>CLEAN-OUTS + MORE.</h2></div><div className="service-list-editorial">{services.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}<Link className="editorial-link" href="/services">View all services →</Link></div></div></section>
<section className="brand-statement" style={{paddingTop:'58px',paddingBottom:'58px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'7%',top:'50%',transform:'translateY(-50%)',fontSize:'190px',lineHeight:1,color:'#090909',opacity:.09}}>✦</span><div className="container" style={{position:'relative',zIndex:1}}><div style={{display:'flex',alignItems:'center',gap:'16px',marginBottom:'18px'}}><Spark size={20}/><span aria-hidden="true" style={{display:'block',height:'1px',width:'80px',background:'#090909',opacity:.4}}/></div><h2>YOU&apos;LL NEVER<br/>SEE IT AGAIN.</h2></div></section>
<section className="section process-section" style={{paddingTop:'82px',paddingBottom:'82px'}}><div className="container"><div className="process-intro"><div style={{display:'flex',alignItems:'center',gap:'12px',marginBottom:'8px'}}><Spark size={13}/><span aria-hidden="true" style={{display:'block',height:'1px',width:'44px',background:'var(--gold-soft)',opacity:.55}}/></div><h2>THREE STEPS.<br/>THAT&apos;S IT.</h2><p className="section-lead">Every job is different. Send us photos of what you need gone and we&apos;ll review the load, confirm availability and provide a quote.</p></div><div className="process-grid"><article><span>01</span><h3>Send us what you need gone.</h3><p>Share photos, your location and a quick description.</p></article><article><span>02</span><h3>Get your quote.</h3><p>We review the job and confirm pricing and availability.</p></article><article><span>03</span><h3>We handle the rest.</h3><p>We show up, load it and haul it away.</p></article></div></div></section>
<section className="section work-section" style={{paddingTop:'82px',paddingBottom:'82px'}}><div className="container"><div className="editorial-split work-heading"><div><div className="eyebrow">Our Work</div><h2>THE JUNK WAS THERE.<br/>NOW IT&apos;S NOT.</h2></div><div><p className="section-lead">Real transformations from completed Disappear It jobs throughout Metro Atlanta. Before-and-after photos are shown together so you can see the full result.</p><Link className="editorial-link light" href="/our-work">See our work →</Link></div></div><div className="work-showcase" style={{gridTemplateColumns:'1fr 1fr'}}><div className="work-stack"><div className="photo-card"><img src="/images/dunwoody-cleanout-before.png" alt="Dunwoody Crossing cleanout before"/><span>Dunwoody Crossing · Before</span></div><div className="photo-card"><img src="/images/dunwoody-cleanout-after.png" alt="Dunwoody Crossing cleanout after"/><span>Dunwoody Crossing · After</span></div><div className="photo-card"><img src="/images/dunwoody-crossing.PNG" alt="Disappear It at Dunwoody Crossing"/><span>Dunwoody Crossing · On Site</span></div></div><div className="work-stack"><div className="photo-card"><img src="/images/hapeville-junk-removal-before.png" alt="Hapeville junk removal before"/><span>Hapeville · Before</span></div><div className="photo-card"><img src="/images/hapeville-junk-removal-after.png" alt="Hapeville junk removal after"/><span>Hapeville · After</span></div></div></div></div></section>
<section className="section owner-section" style={{paddingTop:'74px',paddingBottom:'74px',background:'#0c0c0c',borderTop:'1px solid rgba(255,255,255,.1)',borderBottom:'1px solid rgba(255,255,255,.1)',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',left:'3%',bottom:'-34px',fontSize:'150px',lineHeight:1,color:'var(--gold-soft)',opacity:.045}}>✦</span><div className="container" style={{display:'grid',gridTemplateColumns:'minmax(0,1.45fr) minmax(220px,.55fr)',gap:'clamp(36px,7vw,92px)',alignItems:'center',position:'relative',zIndex:1}}><div className="owner-copy" style={{maxWidth:'720px'}}><div className="eyebrow">Owner Operated</div><h2 style={{marginBottom:'22px'}}>LOCAL. RELIABLE.<br/>BUILT TO GET IT GONE.</h2><p style={{maxWidth:'640px',color:'#b9b1a6',margin:'0 0 12px'}}>Disappear It is locally owned and operated by Aaron Miller, serving homes, apartments, property managers and businesses across Metro Atlanta with dependable junk removal and clean-out support.</p><p style={{maxWidth:'640px',color:'#b9b1a6',margin:'0'}}>From single-item pickups to larger clean-outs, the goal is simple: show up, handle the heavy work and leave you with your space back.</p></div><figure style={{margin:0,width:'min(100%,280px)',justifySelf:'end',alignSelf:'end'}}><img src="/images/disappear-it-ceo.jpeg" alt="Aaron Miller, owner of Disappear It Junk & Trash Removal" style={{width:'100%',height:'auto',display:'block',objectFit:'cover'}}/><figcaption style={{paddingTop:'14px',borderTop:'1px solid rgba(255,255,255,.14)',marginTop:'14px'}}><strong style={{display:'block',fontSize:'.88rem',letterSpacing:'.04em'}}>Aaron Miller</strong><span style={{display:'block',fontSize:'.65rem',letterSpacing:'.12em',textTransform:'uppercase',color:'#9f978c',marginTop:'4px'}}>Owner · Disappear It Junk & Trash Removal</span></figcaption></figure></div></section>
<section className="commercial-section" style={{paddingTop:'74px',paddingBottom:'74px'}}><div className="container commercial-grid"><div><div className="eyebrow dark">Commercial</div><h2>BUILT FOR BIGGER JOBS.</h2></div><div><p>Reliable junk removal and clean-out support for apartment communities, property managers and businesses.</p><Link className="btn btn-dark" href="/commercial">Commercial Services →</Link></div></div></section>
<section className="section area-section" style={{paddingTop:'82px',paddingBottom:'82px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'5%',bottom:'-28px',fontSize:'145px',lineHeight:1,color:'var(--gold-soft)',opacity:.045}}>✦</span><div className="container editorial-split" style={{position:'relative',zIndex:1}}><div><div className="eyebrow">Service Area</div><h2>METRO ATLANTA<br/>+ SURROUNDING AREAS.</h2><p className="section-lead">These are communities we serve frequently, but service is not limited to this list. Send your location and we&apos;ll confirm availability.</p></div><div className="area-list">{serviceAreas.map(area=><span key={area}>{area}</span>)}</div></div></section>
<section className="final-cta" style={{paddingTop:'64px',paddingBottom:'64px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',left:'4%',top:'50%',transform:'translateY(-50%)',fontSize:'120px',lineHeight:1,color:'#090909',opacity:.07}}>✦</span><div className="container cta-grid" style={{position:'relative',zIndex:1}}><div><h2>READY TO CLEAR IT OUT?</h2><p>Fast. Reliable. Professional. Licensed + insured.</p></div><div className="cta-actions"><Link className="btn btn-dark" href="/contact">Get a Free Quote →</Link><a className="cta-phone" href="tel:+14705402892">Call Us</a><a className="cta-phone" href="mailto:junkdisappears@gmail.com">Email Us</a></div></div></section>
</>}
