import Link from 'next/link';
import ServicesStrip from '../components/ServicesStrip';

const services = [
  ['Junk Removal','Single items, bulk junk and full-load removal.'],
  ['Eviction Clean-outs','Fast property clear-outs when you need the space ready.'],
  ['Apartment + House Clean-outs','Move-outs, whole-home clean-outs and unwanted contents.'],
  ['Construction Debris','Non-hazardous renovation and construction debris removal.'],
  ['Trash Removal','Bulk trash, bagged waste and unwanted items hauled away.'],
  ['And More','Furniture, appliances, garage junk, outdoor items and commercial loads.'],
];
const serviceAreas = ['Fayetteville, GA','Jonesboro, GA','Stockbridge, GA','McDonough, GA','Morrow, GA','Fairburn, GA','Atlanta, GA','South Fulton, GA','College Park, GA','Riverdale, GA','East Point, GA','Hapeville, GA'];

const Spark = ({size=18}:{size?:number}) => <span aria-hidden="true" style={{display:'inline-block',fontSize:size,lineHeight:1,color:'var(--gold-soft)'}}>✦</span>;

const TrustIcon = ({type}:{type:'shield'|'home'|'building'|'pin'}) => {
  if(type==='shield') return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3 26 7v7c0 7-4 12-10 15C10 26 6 21 6 14V7l10-4Z"/><path d="m11.5 15.5 3 3 6-7"/></svg>;
  if(type==='home') return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="m4 15 12-10 12 10"/><path d="M7 13v15h18V13"/><path d="M13 28v-8h6v8"/></svg>;
  if(type==='building') return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 28V5h18v23"/><path d="M4 28h24M11 10h3M18 10h3M11 15h3M18 15h3M11 20h3M18 20h3"/></svg>;
  return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M26 13c0 8-10 16-10 16S6 21 6 13a10 10 0 1 1 20 0Z"/><circle cx="16" cy="13" r="3"/></svg>;
};

export default function HomePage(){return <>
<section className="hero" style={{position:'relative',minHeight:'clamp(600px,74vh,760px)',display:'flex',alignItems:'center',overflow:'hidden',borderBottom:'1px solid var(--line)',backgroundImage:"url('/images/loaded-truck-haul.png')",backgroundRepeat:'no-repeat',backgroundPosition:'center center',backgroundSize:'cover',backgroundColor:'#080808'}}>
  <div aria-hidden="true" style={{position:'absolute',inset:0,zIndex:0,background:'linear-gradient(90deg,rgba(8,8,8,.72) 0%,rgba(8,8,8,.64) 30%,rgba(8,8,8,.46) 50%,rgba(8,8,8,.22) 72%,rgba(8,8,8,.08) 100%)'}}/>
  <div aria-hidden="true" style={{position:'absolute',inset:0,zIndex:0,background:'linear-gradient(0deg,rgba(8,8,8,.22) 0%,transparent 42%,rgba(8,8,8,.04) 100%)'}}/>
  <div style={{position:'absolute',top:'clamp(24px,3.2vw,44px)',left:'clamp(48px,6vw,104px)',zIndex:2}}><img src="/images/disappear-it-logo.png" alt="Disappear It Junk & Trash Removal" style={{display:'block',width:'clamp(180px,16vw,220px)',height:'auto',filter:'drop-shadow(0 3px 12px rgba(0,0,0,.35))'}}/></div>
  <div className="container" style={{position:'relative',zIndex:1,width:'100%',paddingLeft:'clamp(48px,6vw,104px)',paddingRight:'clamp(28px,4vw,72px)'}}>
    <div style={{width:'min(100%,600px)',padding:'72px 0 30px',textShadow:'0 2px 18px rgba(0,0,0,.42)'}}>
      <h1 style={{maxWidth:'600px'}}>WE HANDLE THE<br/><span>HEAVY STUFF.</span></h1>
      <p style={{maxWidth:'520px',color:'#eee8df'}}>Fast, reliable junk removal and clean-out services throughout Metro Atlanta — so you don&apos;t have to do the heavy lifting.</p>
      <div className="hero-actions"><Link className="btn" href="/contact">Get a Free Quote →</Link><a className="text-link" href="tel:+14705402892">Call Us</a><a className="text-link" href="mailto:junkdisappears@gmail.com">Email Us</a></div>
    </div>
  </div>
</section>
<section className="micro-strip trust-strip"><div className="container micro-grid trust-grid"><div className="trust-item"><TrustIcon type="shield"/><div><strong>Licensed + Insured</strong><span>Professional. Reliable. Ready.</span></div></div><div className="trust-item"><TrustIcon type="home"/><div><strong>Residential</strong><span>Homeowners + Renters</span></div></div><div className="trust-item"><TrustIcon type="building"/><div><strong>Commercial</strong><span>Businesses + Property Teams</span></div></div><div className="trust-item"><TrustIcon type="pin"/><div><strong>Metro Atlanta</strong><span>Local + Surrounding Areas</span></div></div></div></section>
<ServicesStrip />
<section className="section section-cream" style={{paddingTop:'82px',paddingBottom:'82px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'4%',top:'28px',fontSize:'120px',lineHeight:1,color:'var(--gold)',opacity:.055}}>✦</span><div className="container editorial-split"><div><div style={{display:'flex',alignItems:'center',gap:'12px'}}><div className="eyebrow dark">Services</div><span aria-hidden="true" style={{height:'1px',width:'46px',background:'var(--gold)',opacity:.55}}/></div><h2>JUNK, TRASH,<br/>CLEAN-OUTS + MORE.</h2></div><div className="service-list-editorial">{services.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}<Link className="editorial-link" href="/services">View all services →</Link></div></div></section>
<section className="section process-section" style={{paddingTop:'82px',paddingBottom:'82px',background:'#171717'}}><div className="container"><div className="process-intro"><div style={{display:'flex',alignItems:'center',gap:'12px',marginBottom:'8px'}}><Spark size={13}/><span aria-hidden="true" style={{display:'block',height:'1px',width:'44px',background:'var(--gold-soft)',opacity:.55}}/></div><h2>THREE STEPS.<br/>THAT&apos;S IT.</h2><p className="section-lead">Every job is different. Send us photos of what you need gone and we&apos;ll review the load, confirm availability and provide a quote.</p></div><div className="process-grid" style={{borderTop:0,paddingTop:0,gap:'18px'}}><article style={{padding:'30px 28px',background:'#f2eee7',color:'#111',borderTop:'3px solid var(--gold)'}}><span style={{color:'#8b6812'}}>01</span><h3>Send us what you need gone.</h3><p style={{color:'#625d55'}}>Share photos, your location and a quick description.</p></article><article style={{padding:'30px 28px',background:'#f2eee7',color:'#111',borderTop:'3px solid var(--gold)'}}><span style={{color:'#8b6812'}}>02</span><h3>Get your quote.</h3><p style={{color:'#625d55'}}>We review the job and confirm pricing and availability.</p></article><article style={{padding:'30px 28px',background:'#f2eee7',color:'#111',borderTop:'3px solid var(--gold)'}}><span style={{color:'#8b6812'}}>03</span><h3>We handle the rest.</h3><p style={{color:'#625d55'}}>We show up, load it and haul it away.</p></article></div></div></section>
<section className="section work-section" style={{paddingTop:'82px',paddingBottom:'44px'}}><div className="container"><div className="editorial-split work-heading"><div><div className="eyebrow">Our Work</div><h2>THE JUNK WAS THERE.<br/>NOW IT&apos;S NOT.</h2></div><div><p className="section-lead">Real transformations from completed Disappear It jobs throughout Metro Atlanta.</p><Link className="editorial-link light" href="/our-work">See our work →</Link></div></div><div className="work-showcase" style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'18px'}}><div className="photo-card"><img src="/images/dunwoody-cleanout-before.png" alt="Property management cleanout job"/></div><div className="photo-card"><img src="/images/dunwoody-cleanout-after.png" alt="Completed property management cleanout job"/></div><div className="photo-card"><img src="/images/backyard-cleanout-before.png" alt="Commercial cleanout job"/></div><div className="photo-card"><img src="/images/backyard-cleanout-after.png" alt="Completed commercial cleanout job"/></div><div className="photo-card"><img src="/images/shed-demolition-before.png" alt="Shed demolition job"/></div><div className="photo-card"><img src="/images/shed-demoliton-after.png" alt="Completed shed demolition job"/></div></div></div></section>
<section className="brand-statement" style={{padding:'36px 0',position:'relative',overflow:'hidden',borderTop:'1px solid rgba(9,9,9,.14)',borderBottom:'1px solid rgba(9,9,9,.14)'}}>
  <div className="container" style={{position:'relative',zIndex:1,display:'grid',gridTemplateColumns:'minmax(0,1.35fr) minmax(220px,.65fr)',gap:'clamp(30px,6vw,86px)',alignItems:'center'}}>
    <div>
      <div style={{display:'flex',alignItems:'center',gap:'14px',marginBottom:'10px'}}><span aria-hidden="true" style={{display:'block',height:'1px',width:'clamp(68px,8vw,116px)',background:'#090909',opacity:.45}}/><span style={{fontSize:'.62rem',letterSpacing:'.18em',textTransform:'uppercase',fontWeight:600}}>Our Catchphrase</span></div>
      <h2 style={{margin:0,maxWidth:'860px',lineHeight:.84}}><span style={{display:'block',fontFamily:'var(--font-display)',fontSize:'clamp(4.1rem,7vw,7.2rem)',fontWeight:700,letterSpacing:'-.035em'}}>YOU&apos;LL</span><span style={{display:'inline-block',fontFamily:'var(--font-script)',fontSize:'clamp(5.4rem,9vw,9.4rem)',fontWeight:400,lineHeight:.68,margin:'-.04em 0 .02em .08em'}}>Never</span><span style={{display:'block',fontFamily:'var(--font-display)',fontSize:'clamp(4.1rem,7vw,7.2rem)',fontWeight:700,letterSpacing:'-.035em'}}>SEE IT AGAIN.</span></h2>
      <p style={{margin:'18px 0 0',fontSize:'.78rem',letterSpacing:'.12em',textTransform:'uppercase',fontWeight:600}}>Junk gone. Space back. Just like that.</p>
    </div>
    <div style={{justifySelf:'end',width:'min(100%,310px)',display:'grid',placeItems:'center'}}>
      <div style={{width:'100%',padding:'18px',border:'1px solid rgba(9,9,9,.14)',background:'rgba(255,255,255,.1)'}}><img src="/images/disappear-it-logo.png" alt="Disappear It Junk & Trash Removal" style={{width:'100%',height:'auto',display:'block',filter:'brightness(0)',opacity:.88}}/></div>
    </div>
  </div>
</section>
<section className="section owner-section" style={{paddingTop:'74px',paddingBottom:'74px',background:'#0c0c0c',borderTop:'1px solid rgba(255,255,255,.1)',borderBottom:'1px solid rgba(255,255,255,.1)',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',left:'3%',bottom:'-34px',fontSize:'150px',lineHeight:1,color:'var(--gold-soft)',opacity:.045}}>✦</span><div className="container" style={{display:'grid',gridTemplateColumns:'minmax(0,1.45fr) minmax(220px,.55fr)',gap:'clamp(36px,7vw,92px)',alignItems:'center',position:'relative',zIndex:1}}><div className="owner-copy" style={{maxWidth:'720px'}}><div className="eyebrow">Owner Operated</div><h2 style={{marginBottom:'22px'}}>LOCAL. RELIABLE.<br/>BUILT TO GET IT GONE.</h2><p style={{maxWidth:'640px',color:'#b9b1a6',margin:'0 0 12px'}}>Disappear It is locally owned and operated by Aaron Miller, serving homes, apartments, property managers and businesses across Metro Atlanta with dependable junk removal and clean-out support.</p><p style={{maxWidth:'640px',color:'#b9b1a6',margin:'0'}}>From single-item pickups to larger clean-outs, the goal is simple: show up, handle the heavy work and leave you with your space back.</p></div><figure style={{margin:0,width:'min(100%,280px)',justifySelf:'end',alignSelf:'end'}}><img src="/images/disappear-it-ceo.jpeg" alt="Aaron Miller, owner of Disappear It Junk & Trash Removal" style={{width:'100%',height:'auto',display:'block',objectFit:'cover'}}/><figcaption style={{paddingTop:'14px',borderTop:'1px solid rgba(255,255,255,.14)',marginTop:'14px'}}><strong style={{display:'block',fontSize:'.88rem',letterSpacing:'.04em'}}>Aaron Miller</strong><span style={{display:'block',fontSize:'.65rem',letterSpacing:'.12em',textTransform:'uppercase',color:'#9f978c',marginTop:'4px'}}>Owner · Disappear It Junk & Trash Removal</span></figcaption></figure></div></section>
<section className="commercial-section" style={{paddingTop:'74px',paddingBottom:'74px'}}><div className="container commercial-grid"><div><div className="eyebrow dark">Commercial</div><h2>BUILT FOR BIGGER JOBS.</h2></div><div><p>Reliable junk removal and clean-out support for apartment communities, property managers and businesses.</p><Link className="btn btn-dark" href="/commercial">Commercial Services →</Link></div></div></section>
<section className="section area-section" style={{paddingTop:'82px',paddingBottom:'82px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',right:'5%',bottom:'-28px',fontSize:'145px',lineHeight:1,color:'var(--gold-soft)',opacity:.045}}>✦</span><div className="container editorial-split" style={{position:'relative',zIndex:1}}><div><div className="eyebrow">Service Area</div><h2>METRO ATLANTA<br/>+ SURROUNDING AREAS.</h2><p className="section-lead">These are communities we serve frequently, but service is not limited to this list. Send your location and we&apos;ll confirm availability.</p></div><div className="area-list">{serviceAreas.map(area=><span key={area}>{area}</span>)}</div></div></section>
<section className="final-cta" style={{paddingTop:'64px',paddingBottom:'64px',position:'relative',overflow:'hidden'}}><span aria-hidden="true" style={{position:'absolute',left:'4%',top:'50%',transform:'translateY(-50%)',fontSize:'120px',lineHeight:1,color:'#090909',opacity:.07}}>✦</span><div className="container cta-grid" style={{position:'relative',zIndex:1}}><div><h2>READY TO CLEAR IT OUT?</h2><p>Fast. Reliable. Professional. Licensed + Insured.</p></div><div className="cta-actions"><Link className="btn btn-dark" href="/contact">Get a Free Quote →</Link><a className="cta-phone" href="tel:+14705402892">Call Us</a><a className="cta-phone" href="mailto:junkdisappears@gmail.com">Email Us</a></div></div></section>
</>}
